import { flushNow, getDb } from './db/index'

/**
 * HISTORICAL ORPHAN CLEANUP (`electron . --f2f-orphan-cleanup`).
 *
 * ── WHAT LEFT THESE BEHIND ───────────────────────────────────────────
 *
 * `PRAGMA foreign_keys` is a connection setting, and sql.js reopens the
 * connection on every `export()`. Enforcement was therefore off for the
 * whole working life of the app, so `ON DELETE CASCADE` never fired and
 * every deleted project left its rows behind. That is fixed at the source;
 * this only deals with what accumulated before the fix.
 *
 * ── THE RULE ─────────────────────────────────────────────────────────
 *
 * Deletes rows belonging to PROVEN SMOKE-OWNED project ids, and nothing
 * else. Specifically it will not touch:
 *
 *   - any row belonging to a live project;
 *   - orphans whose id is a real UUID, which is what a project created
 *     through the app gets. Those may be the remains of a project the
 *     operator deleted, and are theirs to decide about.
 *
 * ── WHY THE PREFIX IS PROOF HERE ─────────────────────────────────────
 *
 * Smoke project ids are GENERATED from literal prefixes in the suite's own
 * `makeProject()`/`tid()` helpers. A project created through the app gets
 * `crypto.randomUUID()`, which is hex and dashes and cannot begin with
 * "smoke". The id is never derived from a project NAME, so nothing the
 * operator types can produce a matching id.
 *
 * That reasoning is re-verified at run time rather than trusted: the
 * cleanup counts what it is about to delete, deletes by the same
 * predicate, and aborts if the two disagree.
 */

/** Ids generated by the smoke suite. Deliberately anchored and narrow. */
const SMOKE_ID = "(project_id LIKE 'smoke-%' OR project_id LIKE 'smoke_%')"

/** Never a live project, whatever else is true. */
const NOT_LIVE = 'project_id NOT IN (SELECT id FROM projects)'

const CLEANABLE = `${NOT_LIVE} AND ${SMOKE_ID}`

/**
 * Image rows belonging to a live project that is NOT smoke-owned.
 *
 * The number that must not move. Everything else this sweep touches is
 * expected to change; if this changes, it reached the operator's data and
 * the whole thing is rolled back as a failure.
 */
const NON_SMOKE_IMAGE_COUNT = `
  SELECT COUNT(*) FROM project_images
  WHERE project_id IN (
    SELECT id FROM projects WHERE NOT (id LIKE 'smoke-%' OR id LIKE 'smoke_%')
  )`

const TABLES = [
  'project_images',
  'transitions',
  'property_analysis',
  'analysis_reviews',
  'image_overrides',
  'generation_cost_entries',
  'queue_jobs'
] as const

interface TableReport {
  table: string
  total: number
  orphaned: number
  cleanable: number
  retained: number
}

function scalar(sql: string): number {
  const result = getDb().exec(sql)[0]
  return Number(result?.values[0]?.[0] ?? 0)
}

export function reportOrphans(): TableReport[] {
  return TABLES.map((table) => {
    const total = scalar(`SELECT COUNT(*) FROM ${table}`)
    const orphaned = scalar(`SELECT COUNT(*) FROM ${table} WHERE ${NOT_LIVE}`)
    const cleanable = scalar(`SELECT COUNT(*) FROM ${table} WHERE ${CLEANABLE}`)
    return { table, total, orphaned, cleanable, retained: orphaned - cleanable }
  })
}

/**
 * Delete category-A rows only.
 *
 * `dryRun` reports without writing, which is the default: a destructive
 * sweep across seven tables should have to be asked for twice.
 */
export function cleanSmokeOrphans(dryRun: boolean): void {
  const line = (s = ''): void => console.log(s)
  const before = reportOrphans()

  line('════════════════════════════════════════════════════════════════')
  line(`  ORPHAN CLEANUP — ${dryRun ? 'DRY RUN (nothing will be written)' : 'LIVE'}`)
  line('════════════════════════════════════════════════════════════════')
  line()
  line('table                     total  orphaned  cleanable(A)  retained(B/C)')
  for (const r of before) {
    line(
      `  ${r.table.padEnd(24)}${String(r.total).padStart(5)}${String(r.orphaned).padStart(10)}` +
        `${String(r.cleanable).padStart(14)}${String(r.retained).padStart(15)}`
    )
  }

  // Live smoke projects left behind by a suite run that failed part-way.
  // Counted separately because they are NOT orphans — their rows are
  // perfectly consistent, they simply should not exist any more.
  const abandoned = scalar(
    `SELECT COUNT(*) FROM projects WHERE ${SMOKE_ID.replace(/project_id/g, 'id')}`
  )
  line()
  line(`abandoned smoke projects (live rows, from failed runs): ${abandoned}`)

  // What is deliberately being LEFT — named, so the operator can see it is
  // a decision rather than something the sweep happened to miss.
  line()
  line('retained orphan project ids (NOT smoke-owned — your decision):')
  const retainedIds = getDb().exec(
    `SELECT project_id,
            (SELECT COUNT(*) FROM project_images pi WHERE pi.project_id = g.project_id),
            (SELECT COUNT(*) FROM transitions t WHERE t.project_id = g.project_id)
     FROM (SELECT DISTINCT project_id FROM project_images
           UNION SELECT DISTINCT project_id FROM transitions) g
     WHERE ${NOT_LIVE.replace(/project_id/g, 'g.project_id')}
       AND NOT ${SMOKE_ID.replace(/project_id/g, 'g.project_id')}`
  )[0]
  if (!retainedIds || retainedIds.values.length === 0) {
    line('  (none)')
  } else {
    for (const row of retainedIds.values) {
      line(`  ${row[0]}  images=${row[1]} transitions=${row[2]}`)
    }
  }

  if (dryRun) {
    line()
    line('DRY RUN — nothing written. Re-run with --confirm to apply.')
    line('════════════════════════════════════════════════════════════════')
    return
  }

  // Measured BEFORE the sweep, so the verification afterwards compares
  // against reality rather than against what the sweep believes it did.
  const beforeProjects = scalar('SELECT COUNT(*) FROM projects')
  const beforeNonSmokeImages = scalar(NON_SMOKE_IMAGE_COUNT)

  // ── THE SWEEP ────────────────────────────────────────────────────────
  const db = getDb()
  db.run('BEGIN')
  try {
    // Abandoned smoke PROJECTS first. A suite run that fails part-way
    // leaves its fixtures behind as live project rows — not orphans, so
    // the orphan predicate correctly ignores them, and they would sit
    // there inflating the next run's baseline forever.
    //
    // Deleting the project row is enough now that cascading deletes
    // actually fire; before that fix this would have made the problem
    // worse by converting live rows into orphaned ones.
    db.run(`DELETE FROM projects WHERE ${SMOKE_ID.replace(/project_id/g, 'id')}`)
    for (const table of TABLES) {
      db.run(`DELETE FROM ${table} WHERE ${CLEANABLE}`)
    }
    db.run('COMMIT')
  } catch (err) {
    db.run('ROLLBACK')
    throw err
  }

  const after = reportOrphans()

  // ── VERIFY, DO NOT TRUST ─────────────────────────────────────────────
  //
  // The predicate that counted and the predicate that deleted are the same
  // string, but "the same string" is not proof that the right rows went.
  // Every table must have lost exactly its cleanable count and nothing
  // else — anything different means the sweep reached further than it was
  // supposed to, and that has to be loud.
  line()
  line('result:')
  const problems: string[] = []
  for (let i = 0; i < before.length; i++) {
    const b = before[i]
    const a = after[i]
    line(`  ${b.table.padEnd(24)}${String(b.total).padStart(6)} → ${String(a.total).padStart(6)}  (removed ${b.total - a.total})`)
    // ── THE ONE INVARIANT THAT MATTERS ─────────────────────────────────
    //
    // Row totals are no longer predictable, because deleting an abandoned
    // smoke project cascades to an unknown number of children. So the
    // check is not "how many went" but "did anything that was NOT ours
    // go": the retained non-smoke orphan count must be untouched, and no
    // live non-smoke project may lose a single row.
    if (a.retained !== b.retained) {
      problems.push(`${b.table}: retained (non-smoke) orphans changed ${b.retained} → ${a.retained}`)
    }
  }

  const survivingProjects = scalar('SELECT COUNT(*) FROM projects')
  line(`  ${'projects'.padEnd(24)}${String(beforeProjects).padStart(6)} → ${String(survivingProjects).padStart(6)}  (removed ${beforeProjects - survivingProjects})`)
  if (beforeProjects - survivingProjects !== abandoned) {
    problems.push(
      `projects: expected to remove exactly ${abandoned} abandoned smoke projects, removed ${beforeProjects - survivingProjects}`
    )
  }
  if (beforeNonSmokeImages !== scalar(NON_SMOKE_IMAGE_COUNT)) {
    problems.push('rows belonging to a non-smoke project were removed')
  }

  if (problems.length > 0) {
    console.error()
    console.error('CLEANUP TOUCHED MORE THAN IT SHOULD HAVE:')
    for (const p of problems) console.error(`  - ${p}`)
    throw new Error('Orphan cleanup removed unexpected rows')
  }

  flushNow()
  line()
  line('Verified: every removed row was a proven smoke-owned orphan.')
  line('Non-smoke orphans and all live-project rows are untouched.')
  line('════════════════════════════════════════════════════════════════')
}
